# Generated by Django 5.2.4 on 2025-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_condition_alter_ad_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
