# Generated by Django 5.2.4 on 2025-07-10 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_created_update_alter_ad_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad', verbose_name='Товар для обмена'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad', verbose_name='Ваш товар'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
