# Generated by Django 5.2.4 on 2025-07-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_exchangeproposal_ad_receiver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'verbose_name': 'Предложение обмена', 'verbose_name_plural': 'Предложения обмена'},
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad', verbose_name='Целевой товар'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad', verbose_name='Предлагаемый товар'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10),
        ),
    ]
