# Generated by Django 5.2.4 on 2025-07-14 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_remove_ad_is_active_exchangeproposal_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('clothing', 'Одежда'), ('books', 'Книги'), ('furniture', 'Мебель'), ('home_appliances', 'Бытовая техника'), ('sport', 'Спорт/Отдых'), ('children', 'Детские товары'), ('auto', 'Автотовары'), ('tools', 'Инструменты'), ('cosmetics', 'Косметика/Уход'), ('art', 'Искусство/Хобби'), ('collectibles', 'Коллекционные предметы'), ('musical', 'Музыкальные инструменты'), ('plants', 'Растения'), ('pet_supplies', 'Товары для животных'), ('services', 'Услуги'), ('real_estate', 'Недвижимость'), ('other', 'Другое')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
